name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run your-build-commands

      - name: Deploy to GitHub Pages
        run: |
          git checkout -B gh-pages
          git add your-output-directory
          git commit -m "Publish to GitHub Pages"
          git push -f origin gh-pages
